services:
  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":${MINIO_CONSOLE_PORT-9001}"
    ports:
      - ${MINIO_SERVER_PORT-9000}:9000
      - ${MINIO_CONSOLE_PORT-9001}:9001
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD-minioadmin}
      - MINIO_API_ROOT_ACCESS=${MINIO_ROOT_ACCESS-on}
    volumes:
      - minio-data:/data

volumes:
  minio-data: